{
  config,
  inputs,
  lib,
  ...
}:
#############################################################
#
#  API key for WakaTime
#
#  Decryption only. The key is read by wakatime-cli, which every consumer on
#  these machines goes through: the opencode-wakatime plugin
#  (home/jhl/common/core/opencode.nix), Zed's wakatime extension, and the
#  wakatime cask.
#
#  -- How the key reaches wakatime-cli ------------------------------------
#
#  Not through this file's contents: nothing here renders the key into a
#  config. wakatime-cli supports settings.api_key_vault_cmd -- it runs the
#  string through `sh -c` and takes the TrimSpace'd stdout as the key
#  (loadAPIKey / readAPIKeyFromCommand in pkg/params/params.go) -- so
#  ~/.wakatime.cfg only points at the decrypted path:
#
#    [settings]
#    api_key_vault_cmd = /bin/cat /run/secrets/wakatime/api_key
#
#  That cfg is generated by home/jhl/common/core/wakatime.nix, which also
#  records why it can be managed and what that costs. The pairing to keep in
#  mind here: the key name below and the path in that file are synced by hand,
#  and a rename fails quietly -- wakatime-cli logs to ~/.wakatime/wakatime.log
#  and keeps going rather than erroring out.
#
#  The value has to satisfy ^(waka_)?<uuid-v4>$ -- wakatime-cli rejects
#  anything else with "invalid api key format" before it ever sends a
#  heartbeat, so paste the key from https://wakatime.com/api-key verbatim.
#
#  WARNING: /run/secrets/wakatime/api_key appears in this repo only inside
#     comments -- the real coupling is between the sops.secrets key name below
#     and whatever the user typed into ~/.wakatime.cfg. Renaming the key here
#     silently stops the heartbeats; wakatime-cli logs to ~/.wakatime/*.log
#     rather than failing loudly.
#
#  Filling in the ciphertext:
#    just sops-edit shared
#
#      wakatime:
#          api_key: waka_xxxxxxxx
#
#############################################################
let
  sopsFile = "${inputs.nix-secrets}/secrets/shared.yaml";
in {
  # Same eval-time pre-flight as llm.nix. Note it matches "wakatime:" and not
  # "api_key:" -- key names stay in cleartext, and shared.yaml already carries
  # an api_key under llm, so the narrower string is the only one that actually
  # proves this secret exists.
  assertions = [
    {
      assertion =
        builtins.pathExists sopsFile
        && lib.hasInfix "wakatime:" (builtins.readFile sopsFile);
      message = ''
        hosts/common/optional/darwin/wakatime.nix is imported, but
        secrets/shared.yaml has no wakatime.api_key yet.

          just sops-edit shared

            wakatime:
                api_key: waka_xxxxxxxx

        Then cd ../nix-secrets && git add -A && git commit && git push
        and back here run just update-nix-secrets.

        ~/.wakatime.cfg needs no edit -- home/jhl/common/core/wakatime.nix
        generates it and already points at the decrypted path.
      '';
    }
  ];

  # mode 0400 with owner set to the user: wakatime-cli is spawned by opencode
  # and Zed, both of which run as the user and could not read a root-only file.
  sops.secrets."wakatime/api_key" = {
    inherit sopsFile;
    owner = config.hostSpec.username;
    mode = "0400";
  };
}
