{lib, ...}:
#############################################################
#
#  LLM providers (OpenAI-compatible endpoints)
#
#  The same provider facts feed two consumers:
#    home/jhl/common/core/opencode.nix
#    home/jhl/common/optional/editors/zed.nix
#  Declaring them as options avoids copying the URL and model names into both.
#
#  -- Why the API key is not here ----------------------------------------
#
#  The nix store is **world-readable**, so any key written into a .nix file is
#  effectively leaked to every process on the machine. This only declares
#  *which environment variable holds the key*; the value goes through sops:
#
#    ciphertext  nix-secrets: llm/api_key
#    system side hosts/common/optional/darwin/llm.nix decrypts it to
#                /run/secrets/llm/api_key
#    terminal    home/jhl/common/core/llm.nix exports it in zsh
#    GUI         same file, via a launchd agent running launchctl setenv
#
#  Zed's docs say verbatim "Do not put API keys in settings.json"; it looks for
#  a <PROVIDER_ID>_API_KEY environment variable. opencode understands {env:VAR}
#  substitution inside config values. Conveniently, both can share one variable
#  name.
#
#  -- How envVar is derived (this one bites) -----------------------------
#
#  Zed, in crates/language_models/src/provider/api_compatible.rs:31:
#
#      format!("{}_API_KEY", id).to_case(Case::UpperSnake)
#
#  convert_case's UpperSnake splits words at **lower->upper** boundaries by
#  default, so a camelCase provider name gets broken apart:
#
#      jianyuelab  -> JIANYUELAB_API_KEY
#      JianyueLab  -> JIANYUE_LAB_API_KEY     <- one extra underscore
#      my-provider -> MY_PROVIDER_API_KEY     (the example from Zed's docs)
#
#  The envVar default below is a plain toUpper, which **only matches for
#  all-lowercase or hyphenated names**. A provider name containing capitals
#  must set envVar explicitly -- do not rely on the default.
#
#  How to check: in Zed run `agent: open settings` and open the provider. It
#  prints the variable name it is looking for ("You can also set the
#  {env_var_name} environment variable and restart Zed.").
#
#############################################################
{
  options.llm = {
    apiKeyFile = lib.mkOption {
      type = lib.types.str;
      default = "/run/secrets/llm/api_key";
      description = ''
        Where the decrypted API key lands. Must line up with the sops.secrets
        key name in hosts/common/optional/darwin/llm.nix -- the two are kept in
        sync by hand, so changing one means changing the other.
      '';
    };

    defaultProvider = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        Name of the default provider. opencode's model and Zed's
        agent.default_model / commit_message_model / edit_predictions all point
        at it.

        When left empty, or when that provider has no models refreshed yet,
        neither side writes a default at all -- Zed uses mutableUserSettings
        merge semantics, so writing nothing preserves whatever you picked in
        the UI, which beats writing a default that points at no model.
      '';
    };

    providers = lib.mkOption {
      default = {};
      description = "OpenAI-compatible providers. The key is also the provider name Zed displays.";
      type = lib.types.attrsOf (lib.types.submodule ({
        name,
        config,
        ...
      }: {
        options = {
          apiUrl = lib.mkOption {
            type = lib.types.str;
            example = "https://llm.example.net/v1";
            description = "OpenAI-compatible base URL, including /v1.";
          };

          envVar = lib.mkOption {
            type = lib.types.str;
            default = "${lib.toUpper name}_API_KEY";
            defaultText = lib.literalExpression ''"''${lib.toUpper name}_API_KEY"'';
            description = ''
              Name of the environment variable holding the key. The default
              simply uppercases the whole name, which only matches Zed's own
              derivation for all-lowercase provider names; names containing
              capitals must set this explicitly (see the envVar section in the
              file header).
            '';
          };

          models = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [];
            description = ''
              List of model ids. Generated by `just llm-models` hitting
              /v1/models -- do not hand-write it, the next refresh overwrites
              whatever you put here.

              An empty list means the provider is skipped entirely (neither Zed
              nor opencode generates config for it), so a first rebuild before
              the list has ever been refreshed cannot produce a broken config
              with an empty available_models.
            '';
          };

          defaultModel = lib.mkOption {
            type = lib.types.str;
            default =
              if config.models == []
              then ""
              else builtins.head config.models;
            defaultText = lib.literalExpression "the first entry of models (sorted by id)";
            description = ''
              Default model for this provider. Defaults to the first entry of
              the sorted list, purely so that things work immediately after a
              refresh -- it does not imply that model is the best choice.
              To pin a specific model, set this explicitly.
            '';
          };

          maxTokens = lib.mkOption {
            type = lib.types.int;
            default = 200000;
            description = "Zed's max_tokens / max_completion_tokens.";
          };

          maxOutputTokens = lib.mkOption {
            type = lib.types.int;
            default = 32000;
            description = "Zed's max_output_tokens.";
          };
        };
      }));
    };
  };
}
